name: CI - Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Install Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Set up Xvfb
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1024x768x24 &

      - name: Run UI tests
        run: ./gradlew test